
name: "build maven pull request in ci"
on:
    push:
        branches:
            - "main"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.0.100'
            - name: restore
              run: dotnet restore --project src/Presentation/Nop.Web/Nop.Web.csproj








  
          
          